#!/bin/bash

# Superhero Weight Update Examples
# Make this file executable with: chmod +x examples.sh

echo "🦸 Superhero Weight Update Examples"
echo "=============================================="
echo ""
echo "🎯 RECOMMENDED: Interactive Mode"
echo "--------------------------------"
echo "# Easy mode - walks through each person's predictions"
echo "node updateWeights.js --interactive"
echo ""
echo "# Preview mode - see what would happen without saving"
echo "node updateWeights.js --dry-run --interactive"
echo ""
echo "# Short form"
echo "node updateWeights.js -i"
echo ""

# Show current probabilities
echo "📊 Current probabilities:"
node updateWeights.js --show

echo ""
echo "🎯 How the system works:"
echo "Base rules (always apply):"
echo "  • Become superhero: weight -= 1"
echo "  • Don't become superhero (no guess): weight += 1"
echo ""
echo "Prediction bonuses/penalties (in addition to base rules):"
echo "  • Correct guess: bonus reduction (bigger for unlikely winners)"
echo "  • Wrong guess: penalty increase (minimum +1.2, always worse than no guess)"
echo ""

echo "Example 1: Manual single person updates"
echo "---------------------------------------"
echo "# Johan guessed Sam would win, but Ali actually won"
echo "node updateWeights.js Johan Ali Sam"
echo ""
echo "# Kemila made no guess, Dom won"
echo "node updateWeights.js Kemila Dom"
echo ""
echo "# Dom guessed himself and won (correct guess + became superhero)"
echo "node updateWeights.js Dom Dom Dom"
echo ""

echo "Example 2: Dry run - preview changes without saving"
echo "---------------------------------------------------"
echo "# Preview what would happen if Johan guessed Sam but Ali won"
echo "node updateWeights.js --dry-run Johan Ali Sam"
echo ""
echo "# Preview batch update without making changes"
echo "node updateWeights.js --dry-run --batch '[{\"person\":\"Johan\",\"guess\":\"Sam\"}]' Ali"
echo ""

echo "Example 3: Manual batch update for whole team"
echo "----------------------------------------------"
echo "# Everyone's predictions before the wheel spin:"
echo "# Johan guessed: Sam"
echo "# Ali guessed: Dom"
echo "# Kemila guessed: Ali"
echo "# Dom made no guess"
echo "# Sam guessed: Johan"
echo ""
echo "# Scenario A: Sam actually won"
echo "node updateWeights.js --batch '[{\"person\":\"Johan\",\"guess\":\"Sam\"},{\"person\":\"Ali\",\"guess\":\"Dom\"},{\"person\":\"Kemila\",\"guess\":\"Ali\"},{\"person\":\"Sam\",\"guess\":\"Johan\"}]' Sam"
echo ""
echo "# Note: Dom automatically gets base rules since he's not in predictions list"
echo ""

echo "Example 4: Different winner scenario"
echo "-----------------------------------"
echo "# Same predictions, but Ali won instead:"
echo "node updateWeights.js --batch '[{\"person\":\"Johan\",\"guess\":\"Sam\"},{\"person\":\"Ali\",\"guess\":\"Dom\"},{\"person\":\"Kemila\",\"guess\":\"Ali\"},{\"person\":\"Sam\",\"guess\":\"Johan\"}]' Ali"
echo ""

echo "Example 5: Weight change breakdown"
echo "---------------------------------"
echo "# If current probabilities are Sam=30%, Ali=15%, Dom=25%, Johan=20%, Kemila=10%:"
echo "#"
echo "# Johan guessed Sam (30% chance), Ali won:"
echo "#   - Base: +1 (didn't become superhero)"
echo "#   - Penalty: +2.1 (wrong guess: 1.2 + 0.30 * 3.0 = 2.1)"
echo "#   - Total: +3.1 (big penalty for guessing favorite who lost!)"
echo "#"
echo "# Kemila guessed Ali (15% chance), Ali won:"
echo "#   - Base: +1 (didn't become superhero)"
echo "#   - Bonus: -2.0 (correct guess: 1/0.15 * 0.3 = 2.0)"
echo "#   - Total: -1.0 (nice reward for correct longshot!)"
echo "#"
echo "# Sam guessed Dom (25% chance), Ali won:"
echo "#   - Base: +1 (didn't become superhero)"
echo "#   - Penalty: +1.95 (wrong guess: 1.2 + 0.25 * 3.0 = 1.95)"
echo "#   - Total: +2.95 (moderate penalty)"
echo "#"
echo "# Ali guessed Dom (25% chance), Ali won:"
echo "#   - Base: -1 (became superhero)"
echo "#   - Penalty: +1.95 (wrong guess reduced superhero benefit)"
echo "#   - Total: +0.95 (wrong guess hurt even the winner!)"
echo "#"
echo "# Dom guessed Kemila (10% chance), Ali won:"
echo "#   - Base: +1 (didn't become superhero)"
echo "#   - Penalty: +1.5 (wrong guess: 1.2 + 0.10 * 3.0 = 1.5)"
echo "#   - Total: +2.5 (small penalty for reasonable longshot guess)"

echo ""
echo "💡 Strategic insights:"
echo "- Not guessing is safe: +1 if you don't win, -1 if you do"
echo "- Wrong guesses are always worse than not guessing (minimum +2.2 total penalty)"
echo "- Guessing favorites incorrectly = big penalties (base 1.2 + up to 3.0 more)"
echo "- Guessing longshots incorrectly = smaller penalties (closer to base 1.2)"
echo "- Correct guesses on underdogs give big rewards (inverse probability scaling)"
echo "- Even winners get penalized for wrong guesses"
echo "- The system encourages thoughtful predictions, not just safe bets"

echo ""
echo "🎯 Recommended workflow:"
echo "1. Everyone makes predictions before spinning the wheel"
echo "2. Spin the wheel on wheelofnames.com"
echo "3. Run interactive mode: node updateWeights.js --interactive"
echo "   (It will ask about each person's guess and the winner)"
echo "4. Optional: Use --dry-run first to preview changes"
echo "5. Generate new wheelOfDeathList.txt: node superHero.js"
echo "6. Repeat for next sprint!"
echo ""
echo "💡 Interactive mode sample session:"
echo "Did Johan make a guess? (y/n): y"
echo "Available options: Johan, Ali, Sam, Kemila, Dom"
echo "Who did Johan guess would win? Sam"
echo "✅ Johan guessed Sam"
echo ""
echo "Did Ali make a guess? (y/n): n"
echo "📝 Ali made no guess"
echo "..."
echo "Who actually won the superhero selection? Ali"
echo "🎉 Ali is the new superhero!"

echo ""
echo "💡 Pro tip - use dry run to preview changes:"
echo "node updateWeights.js --dry-run --batch '[predictions]' winner"
echo ""
echo "Check probabilities after updates:"
echo "node updateWeights.js --show"
